In [171]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [194]:
bank1 = pd.read_excel("BANKS2020.xlsx", sheet_name=1)

In [195]:
bank1.head()

,ICICI Bank,Previous Years »,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Standalone Balance Sheet,------------------- in Rs. Cr. ---------------...,NaN,NaN,NaN,NaN
1,NaN,Mar 21,2020,2019,2018,2017
2,EQUITIES AND LIABILITIES,NaN,NaN,NaN,NaN,NaN
3,SHAREHOLDER'S FUNDS,NaN,NaN,NaN,NaN,NaN
4,Equity Share Capital,1386.51,1294.76,1294.76,1289.46,1294.14

In [196]:
#Select data from second row

In [197]:
bank1 = bank1[1:]

In [198]:
bank1.head(2)

,ICICI Bank,Previous Years »,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
1,NaN,Mar 21,2020,2019,2018,2017
2,EQUITIES AND LIABILITIES,NaN,NaN,NaN,NaN,NaN

In [199]:
# Transpose the data

In [200]:
bank_t = bank1.T

In [201]:
bank_t.head(2)

,1,2,3,4,5,6,7,8,9,10,...,81,82,83,84,85,86,87,88,89,90
ICICI Bank,NaN,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,...,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),NaN,NaN,NaN,NaN,NaN,Source : Dion Global Solutions Limited
Previous Years »,Mar 21,NaN,NaN,1386.51,1386.51,0,146122.67,146122.67,147509.18,932522.16,...,24.01,23.67,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [202]:
bank_t.shape

(6, 90)

In [203]:
# step4: Remove columns with nan
bank_t.dropna(how='all', axis=1, inplace=True)

In [204]:
bank_t.shape

(6, 81)

In [205]:
bank_t.head(3)

,1,2,3,4,5,6,7,8,9,10,...,76,77,78,79,80,81,82,83,84,90
ICICI Bank,NaN,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,...,Tax On Dividend,Balance Carried Over To Balance Sheet,Total Appropriations,OTHER INFORMATION,EARNINGS PER SHARE,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),Source : Dion Global Solutions Limited
Previous Years »,Mar 21,NaN,NaN,1386.51,1386.51,0,146122.67,146122.67,147509.18,932522.16,...,0,0,0,NaN,NaN,24.01,23.67,NaN,0,NaN
Unnamed: 2,2020,NaN,NaN,1294.76,1294.76,3114.87,112091.29,115206.16,116504.41,770968.99,...,0,21327.47,25810.38,NaN,NaN,12.28,12.08,NaN,0,NaN

In [206]:
bank_t[1][0]

nan

In [207]:
#Step5 : Convert the first value (nan) in the first columns to Year
bank_t[1][0] = 'Year'

In [208]:
bank_t[1][0]

'Year'

In [209]:
bank_t.head(3)

,1,2,3,4,5,6,7,8,9,10,...,76,77,78,79,80,81,82,83,84,90
ICICI Bank,Year,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,...,Tax On Dividend,Balance Carried Over To Balance Sheet,Total Appropriations,OTHER INFORMATION,EARNINGS PER SHARE,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),Source : Dion Global Solutions Limited
Previous Years »,Mar 21,NaN,NaN,1386.51,1386.51,0,146122.67,146122.67,147509.18,932522.16,...,0,0,0,NaN,NaN,24.01,23.67,NaN,0,NaN
Unnamed: 2,2020,NaN,NaN,1294.76,1294.76,3114.87,112091.29,115206.16,116504.41,770968.99,...,0,21327.47,25810.38,NaN,NaN,12.28,12.08,NaN,0,NaN

In [210]:
bank_t.head(3)

,1,2,3,4,5,6,7,8,9,10,...,76,77,78,79,80,81,82,83,84,90
ICICI Bank,Year,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,...,Tax On Dividend,Balance Carried Over To Balance Sheet,Total Appropriations,OTHER INFORMATION,EARNINGS PER SHARE,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),Source : Dion Global Solutions Limited
Previous Years »,Mar 21,NaN,NaN,1386.51,1386.51,0,146122.67,146122.67,147509.18,932522.16,...,0,0,0,NaN,NaN,24.01,23.67,NaN,0,NaN
Unnamed: 2,2020,NaN,NaN,1294.76,1294.76,3114.87,112091.29,115206.16,116504.41,770968.99,...,0,21327.47,25810.38,NaN,NaN,12.28,12.08,NaN,0,NaN

In [211]:
bank_t1 = bank_t.copy()

### Step7: convert first row into column names

In [212]:
new_header = bank_t1.iloc[0]
bank_t1 = bank_t1[1:] 
bank_t1.columns = new_header

In [213]:
bank_t1.head(3)

ICICI Bank,Year,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,...,Tax On Dividend,Balance Carried Over To Balance Sheet,Total Appropriations,OTHER INFORMATION,EARNINGS PER SHARE,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),Source : Dion Global Solutions Limited
Previous Years »,Mar 21,NaN,NaN,1386.51,1386.51,0,146122.67,146122.67,147509.18,932522.16,...,0,0,0,NaN,NaN,24.01,23.67,NaN,0,NaN
Unnamed: 2,2020,NaN,NaN,1294.76,1294.76,3114.87,112091.29,115206.16,116504.41,770968.99,...,0,21327.47,25810.38,NaN,NaN,12.28,12.08,NaN,0,NaN
Unnamed: 3,2019,NaN,NaN,1294.76,1298.25,0,115206.16,115206.16,116507.9,770968.99,...,0,17879.57,21858.56,NaN,NaN,5.23,5.17,NaN,50,NaN

In [214]:
bank_t1['Symbol'] = bank_t.index[0]

In [118]:
bank_t.columns

Index([                                                      'Year',
                                         'EQUITIES AND LIABILITIES',
                                              'SHAREHOLDER'S FUNDS',
                                             'Equity Share Capital',
                                              'Total Share Capital',
                                              'Revaluation Reserve',
                                             'Reserves and Surplus',
                                       'Total Reserves and Surplus',
                                         'Total ShareHolders Funds',
                                                         'Deposits',
                                                       'Borrowings',
                                 'Other Liabilities and Provisions',
                                    'Total Capital and Liabilities',
                                                           'ASSETS',
                     'Cash and Balances with Reserve Bank of India',
               'Balances with Banks Money at Call and Short Notice',
                                                      'Investments',
                                                         'Advances',
                                                     'Fixed Assets',
                                                     'Other Assets',
                                                     'Total Assets',
                                     'OTHER ADDITIONAL INFORMATION',
                                               'Number of Branches',
                                              'Number of Employees',
                                      'Capital Adequacy Ratios (%)',
                                       'KEY PERFORMANCE INDICATORS',
                                                       'Tier 1 (%)',
                                                       'Tier 2 (%)',
                                                   'ASSETS QUALITY',
                                                        'Gross NPA',
                                                    'Gross NPA (%)',
                                                          'Net NPA',
                                                      'Net NPA (%)',
                                          'Net NPA To Advances (%)',
                              'CONTINGENT LIABILITIES, COMMITMENTS',
                                             'Bills for Collection',
                                           'Contingent Liabilities',
                                                       'ICICI Bank',
                                'Standalone Profit & Loss account ',
                                                                nan,
                                                                nan,
                                                           'INCOME',
                          'Interest / Discount on Advances / Bills',
                                          'Income from Investments',
          'Interest on Balance with RBI and Other Inter-Bank funds',
                                                           'Others',
                                            'Total Interest Earned',
                                                     'Other Income',
                                                     'Total Income',
                                                      'EXPENDITURE',
                                                'Interest Expended',
                         'Payments to and Provisions for Employees',
                                                     'Depreciation',
       'Operating Expenses (excludes Employee Cost & Depreciation)',
                                         'Total Operating Expenses',
                                     'Provision Towards Income Tax',
                                   'Provision Towards Deferred Tax',
                               'Other Provisions and Contingencies',
                               'Total Provisions and Contingencies',
                                                'Total Expenditure',
                                   'Net Profit / Loss for The Year',
                    'Net Profit / Loss After EI & Prior Year Items',
                                    'Profit / Loss Brought Forward',
                 'Total Profit / Loss available for Appropriations',
                                                   'APPROPRIATIONS',
                             'Transfer To / From Statutory Reserve',
                               'Transfer To / From Capital Reserve',
                            'Transfer To / From Investment Reserve',
                    'Transfer To / From Revenue And Other Reserves',
                  'Dividend and Dividend Tax for The Previous Year',
                                            'Equity Share Dividend',
                                                  'Tax On Dividend',
                            'Balance Carried Over To Balance Sheet',
                                             'Total Appropriations',
                                                'OTHER INFORMATION',
                                               'EARNINGS PER SHARE',
                                                  'Basic EPS (Rs.)',
                                                'Diluted EPS (Rs.)',
                                              'DIVIDEND PERCENTAGE',
                                         'Equity Dividend Rate (%)',
                           'Source : Dion Global Solutions Limited'],
      dtype='object', name='ICICI Bank')

In [216]:
bank_t1.head(5)

ICICI Bank,Year,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,...,Balance Carried Over To Balance Sheet,Total Appropriations,OTHER INFORMATION,EARNINGS PER SHARE,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),Source : Dion Global Solutions Limited,Symbol
Previous Years »,Mar 21,NaN,NaN,1386.51,1386.51,0,146122.67,146122.67,147509.18,932522.16,...,0,0,NaN,NaN,24.01,23.67,NaN,0,NaN,ICICI Bank
Unnamed: 2,2020,NaN,NaN,1294.76,1294.76,3114.87,112091.29,115206.16,116504.41,770968.99,...,21327.47,25810.38,NaN,NaN,12.28,12.08,NaN,0,NaN,ICICI Bank
Unnamed: 3,2019,NaN,NaN,1294.76,1298.25,0,115206.16,115206.16,116507.9,770968.99,...,17879.57,21858.56,NaN,NaN,5.23,5.17,NaN,50,NaN,ICICI Bank
Unnamed: 4,2018,NaN,NaN,1289.46,1289.46,3044.51,104029.4,107073.91,108368.04,652919.67,...,18495.26,25522.36,NaN,NaN,10.56,10.46,NaN,75,NaN,ICICI Bank
Unnamed: 5,2017,NaN,NaN,1294.14,1294.14,0,107073.91,107073.91,108368.05,652919.67,...,18744.94,26933.28,NaN,NaN,16.84,16.77,NaN,125,NaN,ICICI Bank

In [217]:
bank_t1.set_index('Symbol', inplace=True)

In [218]:
bank_t1.head(5)

ICICI Bank,Year,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,...,Tax On Dividend,Balance Carried Over To Balance Sheet,Total Appropriations,OTHER INFORMATION,EARNINGS PER SHARE,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),Source : Dion Global Solutions Limited
Symbol,,,,,,,,,,,,,,,,,,,,,
ICICI Bank,Mar 21,NaN,NaN,1386.51,1386.51,0,146122.67,146122.67,147509.18,932522.16,...,0,0,0,NaN,NaN,24.01,23.67,NaN,0,NaN
ICICI Bank,2020,NaN,NaN,1294.76,1294.76,3114.87,112091.29,115206.16,116504.41,770968.99,...,0,21327.47,25810.38,NaN,NaN,12.28,12.08,NaN,0,NaN
ICICI Bank,2019,NaN,NaN,1294.76,1298.25,0,115206.16,115206.16,116507.9,770968.99,...,0,17879.57,21858.56,NaN,NaN,5.23,5.17,NaN,50,NaN
ICICI Bank,2018,NaN,NaN,1289.46,1289.46,3044.51,104029.4,107073.91,108368.04,652919.67,...,8.73,18495.26,25522.36,NaN,NaN,10.56,10.46,NaN,75,NaN
ICICI Bank,2017,NaN,NaN,1294.14,1294.14,0,107073.91,107073.91,108368.05,652919.67,...,0,18744.94,26933.28,NaN,NaN,16.84,16.77,NaN,125,NaN

In [220]:
bank_t1.dropna(how='all', axis=1, inplace=True)

In [221]:
bank_t1.head(5)

ICICI Bank,Year,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,Borrowings,Other Liabilities and Provisions,...,Transfer To / From Investment Reserve,Transfer To / From Revenue And Other Reserves,Dividend and Dividend Tax for The Previous Year,Equity Share Dividend,Tax On Dividend,Balance Carried Over To Balance Sheet,Total Appropriations,Basic EPS (Rs.),Diluted EPS (Rs.),Equity Dividend Rate (%)
Symbol,,,,,,,,,,,,,,,,,,,,,
ICICI Bank,Mar 21,1386.51,1386.51,0,146122.67,146122.67,147509.18,932522.16,91630.96,58770.38,...,0,0,0,0,0,0,0,24.01,23.67,0
ICICI Bank,2020,1294.76,1294.76,3114.87,112091.29,115206.16,116504.41,770968.99,162896.76,47994.99,...,669,0,645.31,0,0,21327.47,25810.38,12.28,12.08,0
ICICI Bank,2019,1294.76,1298.25,0,115206.16,115206.16,116507.9,770968.99,162896.76,47994.99,...,1269.2,350,0,965.13,0,17879.57,21858.56,5.23,5.17,50
ICICI Bank,2018,1289.46,1289.46,3044.51,104029.4,107073.91,108368.04,652919.67,165319.97,37851.46,...,0,700,0,1457.46,8.73,18495.26,25522.36,10.56,10.46,75
ICICI Bank,2017,1294.14,1294.14,0,107073.91,107073.91,108368.05,652919.67,165319.97,37851.46,...,0,0,-6.24,0,0,18744.94,26933.28,16.84,16.77,125

In [222]:
bank_t1.dropna(how='all', axis=0, inplace=True)

In [223]:
bank_t1.head(5)

ICICI Bank,Year,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,Borrowings,Other Liabilities and Provisions,...,Transfer To / From Investment Reserve,Transfer To / From Revenue And Other Reserves,Dividend and Dividend Tax for The Previous Year,Equity Share Dividend,Tax On Dividend,Balance Carried Over To Balance Sheet,Total Appropriations,Basic EPS (Rs.),Diluted EPS (Rs.),Equity Dividend Rate (%)
Symbol,,,,,,,,,,,,,,,,,,,,,
ICICI Bank,Mar 21,1386.51,1386.51,0,146122.67,146122.67,147509.18,932522.16,91630.96,58770.38,...,0,0,0,0,0,0,0,24.01,23.67,0
ICICI Bank,2020,1294.76,1294.76,3114.87,112091.29,115206.16,116504.41,770968.99,162896.76,47994.99,...,669,0,645.31,0,0,21327.47,25810.38,12.28,12.08,0
ICICI Bank,2019,1294.76,1298.25,0,115206.16,115206.16,116507.9,770968.99,162896.76,47994.99,...,1269.2,350,0,965.13,0,17879.57,21858.56,5.23,5.17,50
ICICI Bank,2018,1289.46,1289.46,3044.51,104029.4,107073.91,108368.04,652919.67,165319.97,37851.46,...,0,700,0,1457.46,8.73,18495.26,25522.36,10.56,10.46,75
ICICI Bank,2017,1294.14,1294.14,0,107073.91,107073.91,108368.05,652919.67,165319.97,37851.46,...,0,0,-6.24,0,0,18744.94,26933.28,16.84,16.77,125

# Sheet 2

In [227]:
bank2 = pd.read_excel("BANKS2020.xlsx", sheet_name=2)

In [228]:
bank2 = bank2[1:]

In [229]:
bank_t = bank2.T

In [230]:
bank_t.dropna(how='all', axis=1, inplace=True)

In [231]:
bank_t

,1,2,3,4,5,7,8,9,10,11,...,76,77,78,79,80,81,82,83,84,88
HDFC Bank,NaN,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,Borrowings,...,Tax On Dividend,Balance Carried Over To Balance Sheet,Total Appropriations,OTHER INFORMATION,EARNINGS PER SHARE,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),Source : Dion Global Solutions Limited
Previous Years »,Mar 20,NaN,NaN,548.33,548.33,170437.7,170437.7,170986.03,1147502.29,144628.54,...,0,57492.4,75480.62,NaN,NaN,48.01,47.66,NaN,250,NaN
Unnamed: 2,2020,NaN,NaN,548.33,548.33,170437.69,170437.69,170986.02,1147502.31,144628.54,...,0,49223.3,61531.58,NaN,NaN,78.65,77.87,NaN,750,NaN
Unnamed: 3,2019,NaN,NaN,544.66,544.66,148661.69,148661.69,149206.35,923140.93,117085.12,...,0,40453.42,50155.67,NaN,NaN,67.76,66.84,NaN,650,NaN
Unnamed: 4,2018,NaN,NaN,544.66,544.66,148661.66,148661.66,149206.32,923140.93,117085.13,...,0,32668.94,38077.33,NaN,NaN,57.18,56.43,NaN,550,NaN
Unnamed: 5,2017,NaN,NaN,519.02,519.02,105775.98,105775.98,106295,788770.64,123104.97,...,488.95,23527.69,30924.01,NaN,NaN,48.84,48.26,NaN,475,NaN

In [232]:
bank_t[1][0] = 'Year'

In [233]:
bank_t.head()

,1,2,3,4,5,7,8,9,10,11,...,76,77,78,79,80,81,82,83,84,88
HDFC Bank,Year,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,Borrowings,...,Tax On Dividend,Balance Carried Over To Balance Sheet,Total Appropriations,OTHER INFORMATION,EARNINGS PER SHARE,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),Source : Dion Global Solutions Limited
Previous Years »,Mar 20,NaN,NaN,548.33,548.33,170437.7,170437.7,170986.03,1147502.29,144628.54,...,0,57492.4,75480.62,NaN,NaN,48.01,47.66,NaN,250,NaN
Unnamed: 2,2020,NaN,NaN,548.33,548.33,170437.69,170437.69,170986.02,1147502.31,144628.54,...,0,49223.3,61531.58,NaN,NaN,78.65,77.87,NaN,750,NaN
Unnamed: 3,2019,NaN,NaN,544.66,544.66,148661.69,148661.69,149206.35,923140.93,117085.12,...,0,40453.42,50155.67,NaN,NaN,67.76,66.84,NaN,650,NaN
Unnamed: 4,2018,NaN,NaN,544.66,544.66,148661.66,148661.66,149206.32,923140.93,117085.13,...,0,32668.94,38077.33,NaN,NaN,57.18,56.43,NaN,550,NaN

In [234]:
bank_t2 = bank_t.copy()

In [235]:
bank_t2.columns = bank_t2.iloc[0]

In [236]:
bank_t2 = bank_t2[1:]

In [237]:
bank_t2['Symbol'] = bank_t.index[0]

In [238]:
bank_t2.set_index('Symbol', inplace=True)

In [239]:
bank_t2.head(5)

HDFC Bank,Year,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,Borrowings,...,Tax On Dividend,Balance Carried Over To Balance Sheet,Total Appropriations,OTHER INFORMATION,EARNINGS PER SHARE,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),Source : Dion Global Solutions Limited
Symbol,,,,,,,,,,,,,,,,,,,,,
HDFC Bank,Mar 20,NaN,NaN,548.33,548.33,170437.7,170437.7,170986.03,1147502.29,144628.54,...,0,57492.4,75480.62,NaN,NaN,48.01,47.66,NaN,250,NaN
HDFC Bank,2020,NaN,NaN,548.33,548.33,170437.69,170437.69,170986.02,1147502.31,144628.54,...,0,49223.3,61531.58,NaN,NaN,78.65,77.87,NaN,750,NaN
HDFC Bank,2019,NaN,NaN,544.66,544.66,148661.69,148661.69,149206.35,923140.93,117085.12,...,0,40453.42,50155.67,NaN,NaN,67.76,66.84,NaN,650,NaN
HDFC Bank,2018,NaN,NaN,544.66,544.66,148661.66,148661.66,149206.32,923140.93,117085.13,...,0,32668.94,38077.33,NaN,NaN,57.18,56.43,NaN,550,NaN
HDFC Bank,2017,NaN,NaN,519.02,519.02,105775.98,105775.98,106295,788770.64,123104.97,...,488.95,23527.69,30924.01,NaN,NaN,48.84,48.26,NaN,475,NaN

In [ ]:
bank_all = pd.concat([bank])

In [240]:
bank = pd.DataFrame()

for i in np.arange(1,28):
    df = pd.read_excel('BANKS2020.xlsx', sheet_name=i)
    df = df[1:]
    df = df.T
    df.dropna(how='all', axis=1, inplace=True)
    df.dropna(how='all', axis=0, inplace=True)
    df[1][0] = 'Year'
    df1 = df.copy()
    df1.columns = df1.iloc[0]
    df1 = df1[1:]
    df1['Symbol'] = df.index[0]
    df1.set_index('Symbol', inplace=True)
    df1.dropna(how='all', axis=1, inplace=True)
    df1.dropna(how='all', axis=0, inplace=True)
    df1 = df1.loc[:,df1.columns.notnull()]
    bank = pd.concat([bank, df1])

In [242]:
bank

,Year,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,Borrowings,Other Liabilities and Provisions,...,IDFC First Bank,Federal Bank,City Union Bank,Karur Vysya Bank,DCB Bank,Karnataka Bank,South Indian Bank,OTHER INFORMATION,DIVIDEND PERCENTAGE,Equity Share Application Money
Symbol,,,,,,,,,,,,,,,,,,,,,
ICICI Bank,Mar 21,1386.51,1386.51,0,146122.67,146122.67,147509.18,932522.16,91630.96,58770.38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ICICI Bank,2020,1294.76,1294.76,3114.87,112091.29,115206.16,116504.41,770968.99,162896.76,47994.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ICICI Bank,2019,1294.76,1298.25,0,115206.16,115206.16,116507.9,770968.99,162896.76,47994.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ICICI Bank,2018,1289.46,1289.46,3044.51,104029.4,107073.91,108368.04,652919.67,165319.97,37851.46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ICICI Bank,2017,1294.14,1294.14,0,107073.91,107073.91,108368.05,652919.67,165319.97,37851.46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Union Bank of India,2017.0,1168.57,1168.57,0.0,23928.2,23928.2,25096.77,408501.64,45680.77,8126.82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bank Of Baroda,2020.0,925.37,925.37,NaN,70930.84,70930.84,71856.21,945984.43,93069.31,47005.56,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Bank Of Baroda,2019.0,530.36,530.36,NaN,45410.73,45410.73,45941.1,638689.72,67201.3,24113.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5042.0
Bank Of Baroda,2018.0,530.36,530.36,NaN,42864.41,42864.41,43394.77,591314.82,62571.97,22718.21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Bank Of Baroda,2017.0,462.09,462.09,NaN,39841.16,39841.16,40303.25,601675.17,30611.44,22285.56,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0